# Generated by Django 4.0.5 on 2022-06-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=200)),
                ('post_text', models.TextField(verbose_name='')),
                ('created_date', models.DateTimeField(verbose_name='')),
                ('published_date', models.DateTimeField(verbose_name='')),
            ],
        ),
    ]
